### ISSUE TITLE
AnnotatorJ Fiji update site downgrades ImageJ

### ISSUE THREAD

**Issue by haesleinhuepf** [spreka/annotatorj#2]
Hi @spreka ,

first of all congratulations to this awesome ImageJ plugin.

I was just playing with it and noticed, when I install it to my Fiji via Update site, it downgrades ImageJ core. This is because there is an ij.jar with a one-year old version on your update site. One can see that in the advanced view of the updater:

![image](https://user-images.githubusercontent.com/12660498/97109160-e7ed5a00-16d1-11eb-9c8a-029de2b95bb5.png)

I'm just wondering, does AnnotatorJ really depend on this old version? Otherwise, I would recommend removing it from the update site. 

Thanks!

Best,
Robert

**Comment by spreka** [comment]
@haesleinhuepf Thanks for pointing this one out. It ineed is an old version, the point was to have the minimum version set to 1.52v (using functions introduced in this version) when building and I just followed that version with the update site. It is removed now.

**Comment by haesleinhuepf** [comment]
Great, awesome!

Thanks for the quick response 🙂
