### ISSUE TITLE
AnnotatorjExporter

### ISSUE THREAD

**Issue by kdmishraISU** [spreka/annotatorj#4]
I have exported the ROIs to a zip file with AnnotatorJ, and I use this as my "Browse Annotations" folder for the AnnotaorJExporter folder. But if I select object to export semantic or bounding boxes, then I get the error "Cannot find annotation files in selected folder", even though I see the ROI zip file created from AnnotatorJ clearly in the folder.

**Comment by spreka** [comment]
Hi @kdmishraISU, thank you for reaching out.
This message is shown when either the selected annotation type (e.g. ROI in your case) doesn't have files in the selected folder, or no matching names for the files in the original image folder could be found. Can you please verify that
- both your original image and annotation folder exist, and they have file pairs with the same corresponding names: [image file name].[ext] and [image file name]_ROIs.zip
- the annotation type ROI is selected (in your case)
- at least one export type e.g. semantic or bounding box is selected

When you select the annotation type then click on the browse annotations button and select a folder, the log window prints how many annotation files of the selected kind it found. Similarly, image files found in the original image folder are also printed. If you change the annotation type, you need to browse or press enter on the folders again.

Let me know if this helps.

**Comment by kdmishraISU** [comment]
I'm not sure what you mean by "the annotation type ROI is selected (in your case)". There isn't an option for that (see image). 
![2021-02-28_12-04-46](https://user-images.githubusercontent.com/62356659/109429877-e7d4d200-79c3-11eb-98a3-87fbf667943d.jpg)

**Comment by spreka** [comment]
Oh sorry, I meant "Object to export" on the right (this corresponds to annotation types in AnnotatorJ), where you should select **"ROI"** in your case. It is now currently looking for [something].tiff files in the folder you selected because "semantic" is the current object type.
