### ISSUE TITLE
Problem with exporting

### ISSUE THREAD

**Issue by swathi24prabhu** [spreka/annotatorj#5]
I have used instance annotation. Is it possible to save the annotated image? and exported image looks complete black image. Can any one help me out?

Input image
![image](https://user-images.githubusercontent.com/61306551/118789676-a3feb400-b8b2-11eb-9159-1750bd60c38c.jpg)
After export
![download](https://user-images.githubusercontent.com/61306551/118789520-7d407d80-b8b2-11eb-80df-a92d57705205.jpg)

**Comment by spreka** [comment]
@swathi24prabhu Thank you for reaching out. The exported masks are 16-bit files for multi-labelled export option (this is the default for instance annotation) with increasing intensity values by objects. Default image viewers might not be able to visualize the labels. I would recommend either ImageJ/Fiji (any OS, you can set the intensity range with the keys ctrl+shift+c then adjust maximum if needed) or Irfanview (shift+u) if you are on Windows. If your mask is still completely black, can you check your annotation file ([filename]_ROIs.zip) by loading it in AnnotatorJ to see if you have saved any ROIs in the ROI Manager?

**Comment by swathi24prabhu** [comment]
Thanks a lot. I have increased the intensity range and problem solved.

**Comment by swathi24prabhu** [comment]
Dear sir
Thank you sir problem solved.  A few more questions sir,
1.  Is it not possible to store with increased intensity images by default?
2. Is it possible to store annotations?
3. Is it required to have the image in tif format? because my next button
not working
Thanks and Regards,

Swathi Prabhu,
l

**Comment by spreka** [comment]
@swathi24prabhu 
> 1.  Is it not possible to store with increased intensity images by default?

The 16-bit format ensures that correct intensity values correspond to individual objects when there are more than 255 objects on the image (0: background, 1-255: object labels is the maximum that can be fit to an 8-bit mask). This format is suitable to train most types of deep learning models. 
If this does not work for your application or preference, you can change it in [Annotator_ExportFrameNew.java](https://github.com/spreka/annotatorj/blob/master/src/main/java/org/biomag/annotatorProject/Annotator_ExportFrameNew.java#L1660):
replace `ShortProcessor` with `ByteProcessor` and change the max value from 65535 to 255 in `setMinAndMax` [below it](https://github.com/spreka/annotatorj/blob/master/src/main/java/org/biomag/annotatorProject/Annotator_ExportFrameNew.java#L1666). Other export formats can be changed similarly.
Alternatively, you can export to overlay which will save the ROI outlines to the original image as an overlay for visual inspection - note that this cannot be used for training.

> 2. Is it possible to store annotations?

Annotations are saved to the [filename]_ROIs.zip files (if you use instance annotation) according to ImageJ's ROI structure and can be loaded in the ROI Manager. Does this answer your question?

> 3. Is it required to have the image in tif format? because my next button not working

Masks are saved to .tiff files for optimal resolution, input images can be in any commonly used image format (png, bmp, jpg, jpeg, tif, tiff). What do you mean your next button doesn't work? If you open the mask image file with the Open button in AnnotatorJ, it opens like any other image file, and the other image files found in the same folder can be stepped through with the "<" and ">" buttons. If no further image files exist in the same folder, these buttons are inactive - when the selected image is the first in the list, the previous button is inactive, or when it is the last, the next button is inactive. Can you make sure you have further image files in the same folder?
